package projectkmp;

import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import kmp_helper.ConnectionHelper;
import kmp_helper.DBConnection;
import manager.TransaksiManager;
import model.TransaksiModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ROG
 */
public class Transaksi extends javax.swing.JFrame {

    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form AplikasiAdmin
     */
    public Transaksi() {
        initComponents();
        initTableTF();
        loadTF();
    }

    public static DefaultTableModel tableModel;
    public static List<TransaksiModel> listTransaksiModel;

    public void initTableTF() {

        String[] pelangganColumns = new String[]{"No.Stand", "Nama Barang", "Harga Satuan", "Jumblah Beli"};

        int[] columnWidth = { //            135, 135, 135, 135 //lebar tiap kolom
        };

        tableModel = new DefaultTableModel(pelangganColumns, 0);
        tfTabel.setModel(tableModel);
        tfTabel.setRowHeight(20);

        int i = 0;
        for (int width : columnWidth) {
            TableColumn column = tfTabel.getColumnModel().getColumn(i++);
            column.setMaxWidth(width);
            column.setPreferredWidth(width);
        }
    }

    public static void loadTF() {
        listTransaksiModel = new ArrayList<>();
        listTransaksiModel = TransaksiManager.shoTransaksiModel();
        tableModel.setRowCount(0);
        listTransaksiModel.forEach(TransaksiModel -> {
            tableModel.addRow(new Object[]{
                TransaksiModel.getNo_stand(),
                TransaksiModel.getNama_barang(),
                TransaksiModel.getHarga_satuan(),
                TransaksiModel.getJumlah_beli()
            });
        });
    }

    public void getTotalSemua(int[] listHargaBarang){
        try {
//            int totalSemuaBarang = 0;
//            for (int i = 0; i < listHargaBarang.length; i++) {
//                totalSemuaBarang = totalSemuaBarang + listHargaBarang[i];
//            }
//        
//            total.setText(Integer.toString(totalSemuaBarang));
        
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
        public void getTotalBeli(){
        try {
        int jumlah = Integer.parseInt(jumlahBrg.getText());
        int harga = Integer.parseInt(hargaBrg.getText());
        int hasil = (jumlah * harga);
//        total.setText(String.valueOf(hasil));
        totalSemua.setText(String.valueOf(hasil));
        
//        
//        int totalSemuaBarang = 0;
//        for (int i = 0; i < listHargaBarang.length; i++) {
//            totalSemuaBarang = totalSemuaBarang + listHargaBarang[i];
//        }
//        
//        total.setText(Integer.toString(totalSemuaBarang));
//        
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

     public void getTotal() {
        try {
            int totalVar = Integer.parseInt(total.getText());
            int bayar = Integer.parseInt(bayarUang.getText());
            int hasil = ( bayar - totalVar);
            kembaliUang.setText(String.valueOf(hasil));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        noStandTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hargaBrg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlahBrg = new javax.swing.JTextField();
        totalSemua = new javax.swing.JTextField();
        hitungBtn = new javax.swing.JButton();
        tambahBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfTabel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bayarUang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kembaliUang = new javax.swing.JTextField();
        cetak = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        hasil = new javax.swing.JButton();
        barangTxt = new javax.swing.JTextField();
        editBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        setSize(new java.awt.Dimension(1500, 1000));

        jPanel3.setBackground(new java.awt.Color(170, 0, 0));
        jPanel3.setForeground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Year supply of fairy cakes", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSAKSI");

        exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Kembali");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(316, 316, 316))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exit))
                .addGap(26, 26, 26))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No.Stand");

        noStandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noStandTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Barang");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Satuan");

        hargaBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaBrgActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Beli");

        jumlahBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahBrgActionPerformed(evt);
            }
        });

        totalSemua.setEditable(false);
        totalSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSemuaActionPerformed(evt);
            }
        });

        hitungBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hitungBtn.setText("HITUNG");
        hitungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBtnActionPerformed(evt);
            }
        });

        tambahBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tambahBtn.setText("TAMBAH");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        tfTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.Stand", "Nama Barang", "Harga Satuan", "Jumlah Beli"
            }
        ));
        tfTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tfTabel);

        jPanel2.setBackground(new java.awt.Color(102, 0, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rp");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BAYAR");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KEMBALIAN");

        kembaliUang.setEditable(false);

        cetak.setText("cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setForeground(new java.awt.Color(153, 153, 153));
        jButton6.setText("CETAK");

        total.setEditable(false);
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        hasil.setText("HITUNG");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kembaliUang, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(bayarUang)
                            .addComponent(cetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total))))
                .addGap(18, 18, 18)
                .addComponent(hasil)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kembaliUang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hasil))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(bayarUang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel8)))
                .addGap(35, 35, 35)
                .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        barangTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangTxtActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(99, 99, 99)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(noStandTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(hargaBrg)
                                        .addComponent(jumlahBrg)
                                        .addComponent(totalSemua)
                                        .addComponent(barangTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                    .addGap(36, 36, 36)
                                    .addComponent(hitungBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tambahBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(resetBtn)
                        .addGap(49, 49, 49)
                        .addComponent(editBtn)
                        .addGap(53, 53, 53)
                        .addComponent(hapusBtn)))
                .addGap(101, 101, 101)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(noStandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(barangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hargaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jumlahBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hitungBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(tambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editBtn)
                            .addComponent(hapusBtn)
                            .addComponent(resetBtn)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         AplikasiKmp fb = new AplikasiKmp();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void noStandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noStandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noStandTxtActionPerformed

    private void hargaBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaBrgActionPerformed

    private void jumlahBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahBrgActionPerformed

    private void totalSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSemuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSemuaActionPerformed

    private void barangTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barangTxtActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = ConnectionHelper.getConnection();
            //query insert data ke dalam database mysql
            pst = con.prepareStatement("INSERT INTO transaksi (no_stand, nama_barang, harga_satuan, jumlah_beli) VALUES(?,?,?,?)");
            //validasi ketika textField kosong

            if (noStandTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Stand tidak boleh kosong");
            } else if (barangTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Barang tidak boleh kosong");
            } else if (hargaBrg.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Harga tidak boleh kosong");
            } else if (jumlahBrg.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Jumlah tidak boleh kosong");
            } else {
                //digunakan untuk memasukkan data ke masing2 variabel textfield seperti namaTxt, dll

                //misal bingung pst sama rs bisa diliat di variabel diatas
                pst.setString(1, noStandTxt.getText());
                pst.setString(2, barangTxt.getText());
                pst.setString(3, hargaBrg.getText());
                pst.setString(4, jumlahBrg.getText());
                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tfTabel.getModel();
                model.setRowCount(0);
                loadTF();
                //setelah nginput data kasih ini biar textfieldnya kosong lagi
                noStandTxt.setText("");
                barangTxt.setText("");
                hargaBrg.setText("");
                jumlahBrg.setText("");
                totalSemua.setText("");
                
//                int totalSemuaBarang = 0;
//                
                int totalBaris = model.getRowCount();
//                for (int i = 0; i < totalBaris; i++) {
//                    int hargaCurrentBaris = (int) tfTabel.getModel().getValueAt(totalBaris, 3);
//                    totalSemuaBarang = totalSemuaBarang + hargaCurrentBaris;
//                }
////                model.getValueAt(ERROR, NORMAL)
//                

                int[] listHargaBarang = new int[totalBaris];
                int[] listSatuanBarang = new int[totalBaris];
                
                for (int i = 0; i < totalBaris; i++) {
                    String hargaBarisSaatIniTmp = model.getValueAt(i, 2).toString();
                    int hargaBarisSaatIni = Integer.parseInt(hargaBarisSaatIniTmp);
                    
                    String totalBarangSaatIniTmp = model.getValueAt(i, 3).toString();
                    int totalBarangSaatIni = Integer.parseInt(totalBarangSaatIniTmp);
                    listSatuanBarang[i] = totalBarangSaatIni;
                    
                    listHargaBarang[i] = hargaBarisSaatIni * listSatuanBarang[i];
                    System.out.println(listHargaBarang[i]);
                }
                
                int totalSemuaBarang = 0;
                for (int i = 0; i < listHargaBarang.length; i++) {
                    totalSemuaBarang = totalSemuaBarang + listHargaBarang[i];
                }
                
                total.getText();
        
                total.setText(Integer.toString(totalSemuaBarang));
                
//                getTotalSemua(listHargaBarang);
                //setelah daftar muncul pop up dafatar berhasil dan akan tampil frame baru
                JOptionPane.showMessageDialog(null, "Berhasil Menambah Data");
                
                
//                int currentRow = model.getRowCount();
//                model.removeRow(currentRow - 1);
            }

        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void hitungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBtnActionPerformed
        // TODO add your handling code here:
        getTotalBeli();
    }//GEN-LAST:event_hitungBtnActionPerformed

    private void tfTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTabelMouseClicked
        // TODO add your handling code here:
        int i = tfTabel.getSelectedRow();
        TableModel model = tfTabel.getModel();
        noStandTxt.setText(model.getValueAt(i, 0).toString());
        barangTxt.setText(model.getValueAt(i, 1).toString());
        hargaBrg.setText(model.getValueAt(i, 2).toString());
        jumlahBrg.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tfTabelMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = ConnectionHelper.getConnection();
            int row = tfTabel.getSelectedRow();
            String value = (tfTabel.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE transaksi SET no_stand=?,nama_barang=?,harga_satuan=?,jumlah_beli=? WHERE no_stand=" + value;
            if (noStandTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Stand tidak boleh kosong");
            } else if (barangTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Barang tidak boleh kosong");
            } else if (hargaBrg.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Harga tidak boleh kosong");
            } else if (jumlahBrg.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Jumlah tidak boleh kosong");
            } else {
                pst = con.prepareStatement(sql);
                pst.setString(1, noStandTxt.getText());
                pst.setString(2, barangTxt.getText());
                pst.setString(3, hargaBrg.getText());
                pst.setString(4, jumlahBrg.getText());

                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) tfTabel.getModel();
                model.setRowCount(0);
                loadTF();
                noStandTxt.setText("");
                barangTxt.setText("");
                hargaBrg.setText("");
                jumlahBrg.setText("");
                totalSemua.setText("");
                JOptionPane.showMessageDialog(null, "Update Selesai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        try {
            int pilihan = JOptionPane.showConfirmDialog(this, " Apakah anda yakin akan menghapus data ini ?", "Konfirmasi", JOptionPane.WARNING_MESSAGE);
            if (pilihan == JOptionPane.YES_OPTION) {
                Connection con = ConnectionHelper.getConnection();
                int row = tfTabel.getSelectedRow();
                String value = (tfTabel.getModel().getValueAt(row, 0).toString());
                String sql = "DELETE FROM transaksi WHERE no_stand=" + value;
                pst = con.prepareStatement(sql);
                pst.executeUpdate();
                noStandTxt.setText("");
                barangTxt.setText("");
                hargaBrg.setText("");
                jumlahBrg.setText("");
                totalSemua.setText("");
                DefaultTableModel model = (DefaultTableModel) tfTabel.getModel();
                model.setRowCount(0);
                loadTF();
                JOptionPane.showMessageDialog(rootPane, "Data Dihapus");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Pilih Baris Dulu");
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        noStandTxt.setText("");
        barangTxt.setText("");
        hargaBrg.setText("");
        jumlahBrg.setText("");
        totalSemua.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        getTotal ();
    }//GEN-LAST:event_hasilActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
//        try {
            
            Connection con ;
            DBConnection conn = new DBConnection();
            con = conn.getKoneksi();
            String file = "./src/report/NotaBaru.jrxml";
            
            JasperReport jr;
            
               try {
                   jr = JasperCompileManager.compileReport(file);
                   JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                   JasperViewer.viewReport(jp, false);
               } catch (JRException e) {
                   System.out.println(e);
               }
            
//        } catch (SQLException e) {
//            System.out.println(e);
//        }
    }//GEN-LAST:event_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barangTxt;
    private javax.swing.JTextField bayarUang;
    private javax.swing.JButton cetak;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField hargaBrg;
    private javax.swing.JButton hasil;
    private javax.swing.JButton hitungBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahBrg;
    private javax.swing.JTextField kembaliUang;
    private javax.swing.JTextField noStandTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JTable tfTabel;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalSemua;
    // End of variables declaration//GEN-END:variables
}
